[package]
name = "rfce"
version = "0.1.0"
edition = "2021"

[dependencies]
egui = "0.30.0"
log = "0.4.22"
env_logger = "0.11.6"
image = "0.25.5"
num-traits = "0.2.19"
sdl2 = "0.37.0"

[profile.dev]
overflow-checks = false
