[package]
name = "rfce"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.5"
imgui = "0.12.0"
imgui-rs = "1.47.0"
imgui-sdl2-support = "0.13.0"
num-traits = "0.2.19"
sdl2 = "0.37.0"

[profile.dev]
overflow-checks = false
